family_stocks:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: secret
      port: 5433
      dbname: destination_db
      schema: public
      threads: 1
  target: dev