version: 2

sources:
  - name: yfinance_data 
    schema: yfinance_data  
    tables:
      - name: stock_data_hist
  - name: general_dimensions
    schema: general_dimensions
    tables:
      - name: dim_date
      - name: exchange_rates